language: java

dist: trusty
sudo: required

jdk:
- oraclejdk8

install:
# Build ipst-dynamic-simulation
- git clone --branch align_to_powsybl_core_2_4_0 https://github.com/itesla/ipst-dynamic-simulation.git ipst/dynamic-simulation
- pushd ipst/dynamic-simulation && mvn --batch-mode -DskipTests install && popd

script:
- mvn --batch-mode  -Pcheck clean verify
